export const HIDEOUT_CONSTANTS = [
    {
        id: 'backstreet',
        name: 'Backstreet Hideout',
        rarity: 1,
        fromMap: true,
        fromMtx: false,
        location: ['Arcade Map'],
    },
    {
        id: 'baleful',
        name: 'Baleful Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Chamber of Sins Level 2 (Act 7)'],
    },
    {
        id: 'battlescarred',
        name: 'Battle-scarred Hideout',
        rarity: 1,
        fromMap: true,
        fromMtx: false,
        location: ['Promenade Map'],
    },
    {
        id: 'cartographer',
        name: 'Cartographer\'s Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Templar Laboratory'],
    },
    {
        id: 'coastal',
        name: 'Coastal Hideout',
        rarity: 1,
        fromMap: true,
        fromMtx: false,
        location: ['Atoll Map'],
    },
    {
        id: 'coral',
        name: 'Coral Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Cavern of Anger (Act 6)'],
    },
    {
        id: 'desert',
        name: 'Desert Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Oasis'],
    },
    {
        id: 'enlightened',
        name: 'Enlightened Hideout',
        rarity: 1,
        fromMap: true,
        fromMtx: false,
        location: ['Academy Map'],
    },
    {
        id: 'excavated',
        name: 'Excavated Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Crystal Veins'],
    },
    {
        id: 'immaculate',
        name: 'Immaculate Hideout',
        rarity: 1,
        fromMap: true,
        fromMtx: false,
        location: ['Ivory Temple Map'],
    },
    {
        id: 'lush',
        name: 'Lush Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Dread Thicket (Act 2)'],
    },
    {
        id: 'luxurious',
        name: 'Luxurious Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Bath House'],
    },
    {
        id: 'skeletal',
        name: 'Skeletal Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Ossuary (Act 10)'],
    },
    {
        id: 'stately',
        name: 'Stately Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['Oriath Square', 'The Ruined Square'],
    },
    {
        id: 'undercity',
        name: 'Undercity Hideout',
        rarity: 1,
        fromMap: false,
        fromMtx: false,
        location: ['The Sewers'],
    },
    {
        id: 'unearthed',
        name: 'Unearthed Hideout',
        rarity: 1,
        fromMap: true,
        fromMtx: false,
        location: ['Graveyard Map'],
    },

    {
        id: 'alpine',
        name: 'Alpine Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Summit Map'],
    },
    {
        id: 'arboreal',
        name: 'Arboreal Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Terrace Map'],
    },
    {
        id: 'brutal',
        name: 'Brutal Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Tower Map'],
    },
    {
        id: 'celestial',
        name: 'Celestial Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['The Shaper\'s Realm'],
    },
    {
        id: 'divided',
        name: 'Divided Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['The Twilight Temple'],
    },
    {
        id: 'glacial',
        name: 'Glacial Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Iceberg Map'],
    },
    {
        id: 'haunted',
        name: 'Haunted Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Haunted Mansion Map'],
    },
    {
        id: 'overgrown',
        name: 'Overgrown Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Orchard Map'],
    },
    {
        id: 'robberstrench',
        name: 'Robber\'s Trench Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Dig Map'],
    },
    {
        id: 'sanguine',
        name: 'Sanguine Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Crimson Temple Map'],
    },
    {
        id: 'sunken',
        name: 'Sunken Hideout',
        rarity: 10,
        fromMap: true,
        fromMtx: false,
        location: ['Sunken City Map'],
    },

    {
        id: 'sunspire',
        name: 'Sunspire Hideout',
        rarity: 99,
        fromMap: false,
        fromMtx: true,
        location: [],
    },
    {
        id: 'doomguard',
        name: 'Doomguard Hideout',
        rarity: 99,
        fromMap: false,
        fromMtx: true,
        location: [],
    },
    {
        id: 'shaped',
        name: 'Shaped Hideout',
        rarity: 99,
        fromMap: false,
        fromMtx: true,
        location: [],
    },
];

export const HIDEOUT_RARITIES = {
    '1': 'Common',
    '10': 'Rare',
    '99': 'MTX-Only',
};

